In [2]:
import numpy as np

a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# 2D and 3D
b=np.array([[1,2,3],[4,5,6]])
print(type(b))

<class 'numpy.ndarray'>


In [4]:
# 3D
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# np.random
np.random.random((3,4))

array([[0.84119595, 0.88560688, 0.02754382, 0.51586478],
       [0.75411661, 0.44512655, 0.71250835, 0.01821781],
       [0.77835537, 0.4917328 , 0.51231935, 0.02810229]])

In [12]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attribute

In [14]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# ndim
a1.ndim

1

In [16]:
#shape
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [17]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
a3.size

8

In [19]:
a2.size

12

In [20]:
# itemsize
a3.itemsize

8

In [21]:
a1.itemsize

8

In [22]:
a4=np.arange(10,dtype=np.int32)
a4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [23]:
a4.itemsize

4

In [24]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)

int64
float64
int64
int32


### Changing Datatype

In [25]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [26]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [27]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
# arithmetic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [29]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [30]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [31]:
a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [32]:
# relational
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [33]:
# Vector Operations
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array Functions

In [34]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[14., 37., 71.],
       [96., 99.,  8.],
       [82., 40., 82.]])

In [35]:
np.max(a1)

99.0

In [36]:
np.sum(a1)

529.0

In [37]:
np.product(a1)

752094164828160.0

In [38]:
# 0 -> col and 1 -> row
np.max(a1,axis=1)

array([71., 99., 82.])

In [40]:
# mean/median/std/var
np.mean(a1)
np.mean(a1,axis=1)

array([40.66666667, 67.66666667, 68.        ])

In [41]:
# trigonometric functions
np.sin(a1)

array([[ 0.99060736, -0.64353813,  0.95105465],
       [ 0.98358775, -0.99920683,  0.98935825],
       [ 0.31322878,  0.74511316,  0.31322878]])

In [42]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [43]:
a3=np.arange(8).reshape(2,2,2)

In [44]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [45]:
a3[1,1,1]

7

In [46]:
a3[1,0,1]

5

In [47]:
a3[0,1,0]

2

In [48]:
a3[0,0,0]

0

In [51]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a1[2:5]

array([2, 3, 4])

In [53]:
a2=np.arange(12,dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [54]:
a2[0,:]

array([0., 1., 2., 3.])

In [55]:
a2[:,1]

array([1., 5., 9.])

In [56]:
a2[1,2]

6.0

In [57]:
a2[1:,1:3]

array([[ 5.,  6.],
       [ 9., 10.]])

In [63]:
a2[::2,::3]

array([[ 0.,  3.],
       [ 8., 11.]])

In [87]:
a2[::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [94]:
a2[1,0::3]

array([4., 7.])

In [97]:
a2[0:2,1:]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [98]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [105]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [116]:
a3[0,1]

array([3, 4, 5])

In [117]:
a3[1,:,1]

array([10, 13, 16])

In [118]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [123]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [128]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [129]:
a2
for i in a2:
    print(i)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [130]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [131]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [133]:
# Transpose
np.transpose(a2)

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [135]:
a2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [136]:
# ravel
a2.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

### Stacking

In [137]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [138]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [139]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [140]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [141]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [142]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [144]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]