### np.sort

In [1]:
import numpy as np

a=np.random.randint(1,100,15)
a

array([50, 29, 19, 49, 77, 64, 44, 51,  7, 57, 68, 13, 67, 21, 35])

In [2]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[58, 32, 38, 74],
       [34, 27, 98, 84],
       [75, 83, 64, 73],
       [37, 72, 68, 32],
       [31,  3, 39, 38],
       [32, 12, 73, 49]])

In [3]:
np.sort(a)

array([ 7, 13, 19, 21, 29, 35, 44, 49, 50, 51, 57, 64, 67, 68, 77])

In [4]:
np.sort(b)

array([[32, 38, 58, 74],
       [27, 34, 84, 98],
       [64, 73, 75, 83],
       [32, 37, 68, 72],
       [ 3, 31, 38, 39],
       [12, 32, 49, 73]])

In [5]:
np.sort(b,axis=0)

array([[31,  3, 38, 32],
       [32, 12, 39, 38],
       [34, 27, 64, 49],
       [37, 32, 68, 73],
       [58, 72, 73, 74],
       [75, 83, 98, 84]])

In [6]:
np.sort(a)[::-1]

array([77, 68, 67, 64, 57, 51, 50, 49, 44, 35, 29, 21, 19, 13,  7])

### np.append

In [7]:
np.append(a,200)

array([ 50,  29,  19,  49,  77,  64,  44,  51,   7,  57,  68,  13,  67,
        21,  35, 200])

In [9]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[58., 32., 38., 74.,  1.],
       [34., 27., 98., 84.,  1.],
       [75., 83., 64., 73.,  1.],
       [37., 72., 68., 32.,  1.],
       [31.,  3., 39., 38.,  1.],
       [32., 12., 73., 49.,  1.]])

### np.concatenate

In [10]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [12]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

In [13]:
e=np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [15]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

In [17]:
a.shape

(15,)

In [18]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [20]:
np.expand_dims(a,axis=1)

array([[50],
       [29],
       [19],
       [49],
       [77],
       [64],
       [44],
       [51],
       [ 7],
       [57],
       [68],
       [13],
       [67],
       [21],
       [35]])

### np.where

In [21]:
a

array([50, 29, 19, 49, 77, 64, 44, 51,  7, 57, 68, 13, 67, 21, 35])

In [22]:
# find all indices with value greater than 50.
np.where(a>50)

(array([ 4,  5,  7,  9, 10, 12]),)

In [23]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([50, 29, 19, 49,  0,  0, 44,  0,  7,  0,  0, 13,  0, 21, 35])

In [24]:
np.where(a%2 == 0,0,a)

array([ 0, 29, 19, 49, 77,  0,  0, 51,  7, 57,  0, 13, 67, 21, 35])

In [25]:
np.where(a%7!=0,0,a)

array([ 0,  0,  0, 49, 77,  0,  0,  0,  7,  0,  0,  0,  0, 21, 35])

## np.argmax

In [26]:
a

array([50, 29, 19, 49, 77, 64, 44, 51,  7, 57, 68, 13, 67, 21, 35])

In [27]:
np.argmax(a)

4

In [28]:
b

array([[58, 32, 38, 74],
       [34, 27, 98, 84],
       [75, 83, 64, 73],
       [37, 72, 68, 32],
       [31,  3, 39, 38],
       [32, 12, 73, 49]])

In [31]:
np.argmax(b,axis=0)

array([2, 2, 1, 1])

# np.cumsum

In [32]:
a

array([50, 29, 19, 49, 77, 64, 44, 51,  7, 57, 68, 13, 67, 21, 35])

In [33]:
np.cumsum(a)

array([ 50,  79,  98, 147, 224, 288, 332, 383, 390, 447, 515, 528, 595,
       616, 651])

In [34]:
np.cumsum(b,axis=1)

array([[ 58,  90, 128, 202],
       [ 34,  61, 159, 243],
       [ 75, 158, 222, 295],
       [ 37, 109, 177, 209],
       [ 31,  34,  73, 111],
       [ 32,  44, 117, 166]])

# np.cumprod

In [35]:
np.cumprod(a)

array([                  50,                 1450,                27550,
                    1349950,            103946150,           6652553600,
               292712358400,       14928330278400,      104498311948800,
           5956403781081600,   405035457113548800,  5265460942476134400,
        2297745745419524096, -7087571567318648832, -8257331897928538112])

# np.percentile

In [36]:
np.percentile(a,100)

77.0

# np.histogram

In [38]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 2, 1, 2, 3, 3, 1, 0, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef

In [39]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])

In [40]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin

In [43]:
items=[10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([50])

# np.flip

In [45]:
print(a)
np.flip(a)

[50 29 19 49 77 64 44 51  7 57 68 13 67 21 35]


array([35, 21, 67, 13, 68, 57,  7, 51, 44, 64, 77, 49, 19, 29, 50])

In [46]:
b

array([[58, 32, 38, 74],
       [34, 27, 98, 84],
       [75, 83, 64, 73],
       [37, 72, 68, 32],
       [31,  3, 39, 38],
       [32, 12, 73, 49]])

In [47]:
np.flip(b)

array([[49, 73, 12, 32],
       [38, 39,  3, 31],
       [32, 68, 72, 37],
       [73, 64, 83, 75],
       [84, 98, 27, 34],
       [74, 38, 32, 58]])

# np.put

In [48]:
a

array([50, 29, 19, 49, 77, 64, 44, 51,  7, 57, 68, 13, 67, 21, 35])

In [49]:
np.put(a,[0,1],[110,530])

In [50]:
a

array([110, 530,  19,  49,  77,  64,  44,  51,   7,  57,  68,  13,  67,
        21,  35])

# np.delete

In [51]:
np.delete(a,0)

array([530,  19,  49,  77,  64,  44,  51,   7,  57,  68,  13,  67,  21,
        35])

In [52]:
np.delete(a,[0,1,5])

array([19, 49, 77, 44, 51,  7, 57, 68, 13, 67, 21, 35])

In [53]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [54]:
np.intersect1d(m,n)

array([3, 4, 5])

In [55]:
np.setdiff1d(m,n)

array([1, 2])

In [56]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [60]:
m[np.in1d(m,2)]

array([2])

In [64]:
x = np.array([[1,2,3]])
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])